### ISSUE TITLE
Úkoly za zadání 2

### ISSUE THREAD

**Issue by PetraB1517** [PetraB1517/python-012021#2]
@zabza86  Ahojky, úkoly ze zadání dva jsou hotové ve složce 2 :))

**Comment by zabza86** [comment]
Ahojky :)

Ukol 6, 7: Super, nemam komentar, skvele sis vyporadala s neznamym statem :)

Ukol 8: Opet super :)
Python vzdy zacina pocitat od 0 a tak staci napsat:
```Python
number[:4] 
````
Else vetev nemusime psat, pokud se jedna o True nebo False, nebo pokud to nema zadny vliv na vystup...

```Python
  # else:
  #   return False
```

Pro vypocet ceny posilam zjednodusenou verzi:

```Python
def cena(obsah):
   return 3 * (len(obsah) // 180 + 1)
```

**Comment by zabza86** [comment]
Ukol 9: Skvele vypracovany priklad a ted jak se to da udelat elegantne :)
Pokud ze slovniku smazes stringy, tak se z toho stane obycejna matice int a daji se s ni delat kouzla, jako pocitat sumu za pomoci funkce ci vyjhledavat:

```python
def ohodnot_studenta(znamky):
  # soucet=0
  # pocet=0
  # trojka = False
  # petka = False
  # for key, value in znamky.items():
  #   if type(value) == int:
  #     soucet +=value
  #     pocet += 1
  #     if value == 3:
  #       trojka = True
  #     if value == 5:
  #       petka = True
  # prumer=soucet/pocet

  suma = sum(znamky.values())
  prumer = round(suma / len(znamky), 1)

  # if prumer < 1.5 and trojka == False:
  if prumer < 1.5 and 3 not in znamky.values():
    return "Prospěl s vyznamenáním"
  # elif petka:
  if 5 in znamky.values():
    return "Neprospěl"
  # else:
  return "Prospěl"

print('\033[1m' + "Výsledky maturit: " + '\033[0m')

for student in vysledky:
  # print(student["Jméno"] +": " + ohodnot_studenta(student))
  print( student.pop('Jméno') +": " + ohodnot_studenta(student))
```

**Comment by zabza86** [comment]
Ukol 10:
Pouze maly dodatek, or and se vzdy musi rozepsat, tj, co se porovnava s cim. Pokud je to napsane jako to mas ty, tak prvni podminka vezme cokoliv co se naskytne a nikdy nedojde k zemi Nemecko ci Francie:

```python
  # if zeme == "Česko" or "Slovensko":
  if zeme in ['Česko', 'Slovensko']:
    body += 2
  # elif zeme == "Německo" or "Francie":
  elif zeme == "Německo" or zeme == "Francie":
    body += 1
```

**Comment by PetraB1517** [comment]
Díky za komentář. ten úkol 9 mě teď pobavil, vlastně mi vůbec nedošlo, že na to bude funkce :D resp. je to asi taková moje deformace ze školy, že musím prokázat, že rozumím tomu, co to má dělat, aniž bych si to zjednodušovala. 

Za 10 děkuji, zkoušela jsem to vždy jen napsat do správného pole, ale toto mi nedošlo :) ihned opravuju
