### ISSUE TITLE
Úkoly 7

### ISSUE THREAD

**Issue by PetraB1517** [PetraB1517/python-012021#7]
Ahoj @zabza86 , posílám další úkoly. Musím přiznat, že u těchto jsem nadávala jako špaček. matplotlib má tu dokumentaci takovou poměrně složitou a tím, že se tam ty grafy dají dělat různými způsoby, mě dováděl k šílenství :) :D

**Comment by zabza86** [comment]
Ahojky :)

Dekuji za odevzdani ukolu, jsou super a nemam pro tebe ani jednu zpravicku, jsou proste bozi :)

Mej se krasne :)
